CC=g++
CCFLAGS=-g -pedantic -ansi -Wall -std=c++17

Chief:  main.cpp token.cpp object.cpp diagnostics.cpp utils.cpp operation.cpp program.cpp reference.cpp
	$(CC) $(CCPATH) $(CCFLAGS) -o ../chief main.cpp token.cpp object.cpp diagnostics.cpp utils.cpp operation.cpp program.cpp reference.cpp
	